{% set name = "djangorestframework-queryfields" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/djangorestframework-queryfields-{{ version }}.tar.gz
  sha256: 512516947e2d0f7b132469bc3b96b702653ed032e450d90b6efc0dc7fe031ef7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - django

test:
  imports:
    - drf_queryfields
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/wimglenn/djangorestframework-queryfields
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Allows clients to control which fields will be sent in the API response
  description: |
    Allows clients to control which fields will be sent in the API 
    response
  doc_url: http://djangorestframework-queryfields.readthedocs.io/
  dev_url: https://github.com/wimglenn/djangorestframework-queryfields

extra:
  recipe-maintainers:
    - jan-janssen
